# 二、错误处理机制

[[_TOC_]]

## 1. 错误

### (1) 错误对象

`执行代码期间`错误发生时会抛出相应类型的错误对象

#### ① Error

基类型，其他所有错误类型都继承自该类型，主要目的是供开发人员抛出自定义错误

#### ② URIError

使用 encodeURL()、decodeURL() 时 URL 格式不正确时抛出，encodeURL()、decodeURL() 的容错性很高，遇到该错误类型的可能性极小

#### ③ EvalError

使用 eval() 发生异常时抛出，实际开发时不建议使用 eval()，遇到该错误类型的可能性极小

#### ④ SyntaxError

语法错误的字符串传入 eval() 时抛出语法错误，语法错误的代码出现在其他地方则会导致代码立即停止执行，不会抛出错误

#### ⑤ RangeError

数值超出相应范围时抛出范围错误

#### ⑥ ReferenceError

找不到对象时抛出引用错误

#### ⑦ TypeError

变量类型不符合要求时抛出类型错误

### (2) 错误事件

任何没有通过 try-catch 语句处理的错误都会触发 `window 对象的 error 事件`，任何浏览器中 onerror 事件处理程序都`不会创建 event 对象`，但可以接收三个参数：错误消息、错误所在的 URL 和行号，要指定 onerror 事件处理程序，只能使用 `DOM0 级技术`，不遵循 DOM2 级事件的标准格式

```js
window.onerror = function(msg, url, line){
  console.log(msg);
}
```

## 2. 错误处理

### (1) 区分致命错误和非致命错误

#### 致命错误

① 应用程序无法继续运行、明显影响到用户主要操作、会导致其他连带错误

② 将页面中受到影响的区域替换成说明相应功能无法使用的消息，无需因此打断用户

#### 非致命错误

① 不影响用户主要操作、只影响页面的一部分、可以恢复、重复相同操作可以消除错误

② 发送消息打断用户，停止正在进行的行为，给用户提供一种处理方式

### (2) 抛出错误

#### throw 操作符

用于`随时抛出自定义错误`，手动中断程序执行，抛出错误时，必须指定一个值，值可以是`任意数据类型`，也可以是内置错误类型，用于模拟浏览器错误，还可以利用原型链通过继承 Error 来创建自定义类型

```js
//任意数据类型
throw "something bad happend";

//内置错误类型
throw new Error("something bad happend");

//通过原型链继承Error创建自定义类型
function CustomError(msg){
  this.name = "myMsg";
  this.message = msg;
}
CustomError.prototype = new Error();
throw new CustomError("something bad happend");


function f(arr){
  if(Object.prototype.toString.call(arr) !== "[object Array]"){
    throw new Error("Auguments must be Array");
  }

  for(var i=0; i<arr.length; i++){
      if(arr[i] > 5){
        return arr[i];
      }
  }
  return -1;
}
f("haha"); //Error: Auguments must be Array
```

### (3) 捕获错误

以适当地方式处理错误，避免浏览器以默认方式处理

① try：`可能发生错误`的语句，发生错误立即退出代码执行 catch 块

② catch：`处理错误`的语句，捕捉到错误对象后进行处理，选择是否向下执行

③ finally：`必须执行`的语句，无论是否发生错误

```js
function f(){
  try{
    console.log(0);
    throw new Error("something bad happend");
  } catch(e){
    console.log(e.name + ": " + e.message);
    return true;    //延迟到finally代码块结束再执行
    console.log(1); //不会执行
  } finally{
    console.log(2);
    return false;   //覆盖掉catch中的return语句
    console.log(3); //不会执行
  }
  console.log(4);   //不会执行
}
f(); //0  错误信息  2
```

## 3. 错误日志

在复杂的 Web 应用程序中，推荐将 JS 错误也写回服务器，标明来自前端，将前后端的错误集中起来，方便对错误的分析

### (1) Image 对象

① 所有浏览器都支持 Image 对象，包括不支持 XMLHttpRequest 对象的浏览器

② 避免跨域限制，Ajax 通信无法跨域

③ 记录错误的过程中出问题的概率比较低，大多 Ajax 通信都是由 JS 库提供的包装函数来处理的，如果库本身有问题，错误消息就不可能得到记录

```js
function logError(grade, msg){
  var img = new Image();
  img.src = "log.php?grade=" + encodeURIComponent(grade) + 
            "&msg=" + encodeURIComponent(msg);
}

//只要是使用try-catch-finally语句,就应该把相应错误记录到日志
for(var i=0; i<modules.length; i++){
  try{
    module[i].init();
  } catch(e){
    logError("nonfatal", "module init failed: " + e.massage);
  }
}
```
